modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory (24 is current forge version)
issueTrackerURL="http://github.com/ben_mkiv/creeperfix/issues" #optional
displayURL="https://minecraft.curseforge.com/projects/creeperfix" #optional
#logoFile="creeperfix.png" #optional
credits="ben_mkiv (code), luni (for the inspiration to create this mod)" #optional
authors="ben_mkiv" #optional
license="huh?"
[[mods]] #mandatory
modId="creeperfix" #mandatory
version="${file.jarVersion}" #mandatory
displayName="CreeperFix" #mandatory
#updateJSONURL="" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
disables creeper environment grief from their explosion'''
